/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVersionInfoSdkRecommendations } from './ApiVersionInfoSdkRecommendations';
import {
    ApiVersionInfoSdkRecommendationsFromJSON,
    ApiVersionInfoSdkRecommendationsFromJSONTyped,
    ApiVersionInfoSdkRecommendationsToJSON,
} from './ApiVersionInfoSdkRecommendations';

/**
 * 
 * @export
 * @interface ApiVersionInfo
 */
export interface ApiVersionInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiVersionInfo
     */
    apiMajor?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVersionInfo
     */
    apiLatest?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiVersionInfo
     */
    supportedApiMajors?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ApiVersionInfo
     */
    sunset?: { [key: string]: string; };
    /**
     * 
     * @type {ApiVersionInfoSdkRecommendations}
     * @memberof ApiVersionInfo
     */
    sdkRecommendations?: ApiVersionInfoSdkRecommendations;
    /**
     * 
     * @type {Date}
     * @memberof ApiVersionInfo
     */
    generatedAt?: Date;
}

/**
 * Check if a given object implements the ApiVersionInfo interface.
 */
export function instanceOfApiVersionInfo(value: object): value is ApiVersionInfo {
    return true;
}

export function ApiVersionInfoFromJSON(json: any): ApiVersionInfo {
    return ApiVersionInfoFromJSONTyped(json, false);
}

export function ApiVersionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVersionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'apiMajor': json['api_major'] == null ? undefined : json['api_major'],
        'apiLatest': json['api_latest'] == null ? undefined : json['api_latest'],
        'supportedApiMajors': json['supported_api_majors'] == null ? undefined : json['supported_api_majors'],
        'sunset': json['sunset'] == null ? undefined : json['sunset'],
        'sdkRecommendations': json['sdk_recommendations'] == null ? undefined : ApiVersionInfoSdkRecommendationsFromJSON(json['sdk_recommendations']),
        'generatedAt': json['generated_at'] == null ? undefined : (new Date(json['generated_at'])),
    };
}

export function ApiVersionInfoToJSON(value?: ApiVersionInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'api_major': value['apiMajor'],
        'api_latest': value['apiLatest'],
        'supported_api_majors': value['supportedApiMajors'],
        'sunset': value['sunset'],
        'sdk_recommendations': ApiVersionInfoSdkRecommendationsToJSON(value['sdkRecommendations']),
        'generated_at': value['generatedAt'] == null ? undefined : ((value['generatedAt']).toISOString()),
    };
}

