/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVersionInfoSdkRecommendations
 */
export interface ApiVersionInfoSdkRecommendations {
    /**
     * 
     * @type {string}
     * @memberof ApiVersionInfoSdkRecommendations
     */
    typescript?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVersionInfoSdkRecommendations
     */
    python?: string;
}

/**
 * Check if a given object implements the ApiVersionInfoSdkRecommendations interface.
 */
export function instanceOfApiVersionInfoSdkRecommendations(value: object): value is ApiVersionInfoSdkRecommendations {
    return true;
}

export function ApiVersionInfoSdkRecommendationsFromJSON(json: any): ApiVersionInfoSdkRecommendations {
    return ApiVersionInfoSdkRecommendationsFromJSONTyped(json, false);
}

export function ApiVersionInfoSdkRecommendationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVersionInfoSdkRecommendations {
    if (json == null) {
        return json;
    }
    return {
        
        'typescript': json['typescript'] == null ? undefined : json['typescript'],
        'python': json['python'] == null ? undefined : json['python'],
    };
}

export function ApiVersionInfoSdkRecommendationsToJSON(value?: ApiVersionInfoSdkRecommendations | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'typescript': value['typescript'],
        'python': value['python'],
    };
}

