/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleContentTagsInner } from './ArticleContentTagsInner';
import {
    ArticleContentTagsInnerFromJSON,
    ArticleContentTagsInnerFromJSONTyped,
    ArticleContentTagsInnerToJSON,
} from './ArticleContentTagsInner';

/**
 * 
 * @export
 * @interface ArticleContent
 */
export interface ArticleContent {
    /**
     * 
     * @type {boolean}
     * @memberof ArticleContent
     */
    ok?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    urlHash?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    finalUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    thumbUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    videoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    extractedTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    text?: string;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof ArticleContent
     */
    extractedAt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleContent
     */
    truncated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    headlineSummary?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    fullSummary?: string;
    /**
     * 
     * @type {Array<ArticleContentTagsInner>}
     * @memberof ArticleContent
     */
    tags?: Array<ArticleContentTagsInner>;
}

/**
 * Check if a given object implements the ArticleContent interface.
 */
export function instanceOfArticleContent(value: object): value is ArticleContent {
    return true;
}

export function ArticleContentFromJSON(json: any): ArticleContent {
    return ArticleContentFromJSONTyped(json, false);
}

export function ArticleContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleContent {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
        'urlHash': json['url_hash'] == null ? undefined : json['url_hash'],
        'finalUrl': json['final_url'] == null ? undefined : json['final_url'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'thumbUrl': json['thumb_url'] == null ? undefined : json['thumb_url'],
        'videoUrl': json['video_url'] == null ? undefined : json['video_url'],
        'extractedTitle': json['extracted_title'] == null ? undefined : json['extracted_title'],
        'text': json['text'] == null ? undefined : json['text'],
        'extractedAt': json['extracted_at'] == null ? undefined : json['extracted_at'],
        'truncated': json['truncated'] == null ? undefined : json['truncated'],
        'headlineSummary': json['headline_summary'] == null ? undefined : json['headline_summary'],
        'fullSummary': json['full_summary'] == null ? undefined : json['full_summary'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(ArticleContentTagsInnerFromJSON)),
    };
}

export function ArticleContentToJSON(value?: ArticleContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ok': value['ok'],
        'url_hash': value['urlHash'],
        'final_url': value['finalUrl'],
        'image_url': value['imageUrl'],
        'thumb_url': value['thumbUrl'],
        'video_url': value['videoUrl'],
        'extracted_title': value['extractedTitle'],
        'text': value['text'],
        'extracted_at': value['extractedAt'],
        'truncated': value['truncated'],
        'headline_summary': value['headlineSummary'],
        'full_summary': value['fullSummary'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(ArticleContentTagsInnerToJSON)),
    };
}

