/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleContentTagsInner
 */
export interface ArticleContentTagsInner {
    /**
     * 
     * @type {string}
     * @memberof ArticleContentTagsInner
     */
    tag?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleContentTagsInner
     */
    score?: number;
}

/**
 * Check if a given object implements the ArticleContentTagsInner interface.
 */
export function instanceOfArticleContentTagsInner(value: object): value is ArticleContentTagsInner {
    return true;
}

export function ArticleContentTagsInnerFromJSON(json: any): ArticleContentTagsInner {
    return ArticleContentTagsInnerFromJSONTyped(json, false);
}

export function ArticleContentTagsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleContentTagsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : json['tag'],
        'score': json['score'] == null ? undefined : json['score'],
    };
}

export function ArticleContentTagsInnerToJSON(value?: ArticleContentTagsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tag': value['tag'],
        'score': value['score'],
    };
}

