/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BacktestEmbeddingFilter
 */
export interface BacktestEmbeddingFilter {
    /**
     * 1536-dimensional embedding vector for similarity search
     * @type {Array<number>}
     * @memberof BacktestEmbeddingFilter
     */
    embedding?: Array<number>;
    /**
     * Minimum cosine similarity threshold (0.0–1.0, default 0.75)
     * @type {number}
     * @memberof BacktestEmbeddingFilter
     */
    threshold?: number;
    /**
     * Optional label for this filter
     * @type {string}
     * @memberof BacktestEmbeddingFilter
     */
    label?: string;
}

/**
 * Check if a given object implements the BacktestEmbeddingFilter interface.
 */
export function instanceOfBacktestEmbeddingFilter(value: object): value is BacktestEmbeddingFilter {
    return true;
}

export function BacktestEmbeddingFilterFromJSON(json: any): BacktestEmbeddingFilter {
    return BacktestEmbeddingFilterFromJSONTyped(json, false);
}

export function BacktestEmbeddingFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacktestEmbeddingFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'embedding': json['embedding'] == null ? undefined : json['embedding'],
        'threshold': json['threshold'] == null ? undefined : json['threshold'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function BacktestEmbeddingFilterToJSON(value?: BacktestEmbeddingFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'embedding': value['embedding'],
        'threshold': value['threshold'],
        'label': value['label'],
    };
}

