/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BacktestReplay200ResponseMeta } from './BacktestReplay200ResponseMeta';
import {
    BacktestReplay200ResponseMetaFromJSON,
    BacktestReplay200ResponseMetaFromJSONTyped,
    BacktestReplay200ResponseMetaToJSON,
} from './BacktestReplay200ResponseMeta';
import type { BacktestEvent } from './BacktestEvent';
import {
    BacktestEventFromJSON,
    BacktestEventFromJSONTyped,
    BacktestEventToJSON,
} from './BacktestEvent';

/**
 * 
 * @export
 * @interface BacktestReplay200Response
 */
export interface BacktestReplay200Response {
    /**
     * 
     * @type {boolean}
     * @memberof BacktestReplay200Response
     */
    ok?: boolean;
    /**
     * 
     * @type {Array<BacktestEvent>}
     * @memberof BacktestReplay200Response
     */
    events?: Array<BacktestEvent>;
    /**
     * Cursor for the next page. Pass as `cursor` in the next request.
     * @type {number}
     * @memberof BacktestReplay200Response
     */
    nextCursor?: number;
    /**
     * Whether more events are available after this page
     * @type {boolean}
     * @memberof BacktestReplay200Response
     */
    hasMore?: boolean;
    /**
     * 
     * @type {BacktestReplay200ResponseMeta}
     * @memberof BacktestReplay200Response
     */
    meta?: BacktestReplay200ResponseMeta;
}

/**
 * Check if a given object implements the BacktestReplay200Response interface.
 */
export function instanceOfBacktestReplay200Response(value: object): value is BacktestReplay200Response {
    return true;
}

export function BacktestReplay200ResponseFromJSON(json: any): BacktestReplay200Response {
    return BacktestReplay200ResponseFromJSONTyped(json, false);
}

export function BacktestReplay200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacktestReplay200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(BacktestEventFromJSON)),
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
        'meta': json['meta'] == null ? undefined : BacktestReplay200ResponseMetaFromJSON(json['meta']),
    };
}

export function BacktestReplay200ResponseToJSON(value?: BacktestReplay200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ok': value['ok'],
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(BacktestEventToJSON)),
        'next_cursor': value['nextCursor'],
        'has_more': value['hasMore'],
        'meta': BacktestReplay200ResponseMetaToJSON(value['meta']),
    };
}

