/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BacktestEvent } from './BacktestEvent';
import {
    BacktestEventFromJSON,
    BacktestEventFromJSONTyped,
    BacktestEventToJSON,
} from './BacktestEvent';
import type { BacktestReplayWithEmbeddings200ResponseMeta } from './BacktestReplayWithEmbeddings200ResponseMeta';
import {
    BacktestReplayWithEmbeddings200ResponseMetaFromJSON,
    BacktestReplayWithEmbeddings200ResponseMetaFromJSONTyped,
    BacktestReplayWithEmbeddings200ResponseMetaToJSON,
} from './BacktestReplayWithEmbeddings200ResponseMeta';

/**
 * 
 * @export
 * @interface BacktestReplayWithEmbeddings200Response
 */
export interface BacktestReplayWithEmbeddings200Response {
    /**
     * 
     * @type {boolean}
     * @memberof BacktestReplayWithEmbeddings200Response
     */
    ok?: boolean;
    /**
     * 
     * @type {Array<BacktestEvent>}
     * @memberof BacktestReplayWithEmbeddings200Response
     */
    events?: Array<BacktestEvent>;
    /**
     * 
     * @type {number}
     * @memberof BacktestReplayWithEmbeddings200Response
     */
    nextCursor?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BacktestReplayWithEmbeddings200Response
     */
    hasMore?: boolean;
    /**
     * 
     * @type {BacktestReplayWithEmbeddings200ResponseMeta}
     * @memberof BacktestReplayWithEmbeddings200Response
     */
    meta?: BacktestReplayWithEmbeddings200ResponseMeta;
}

/**
 * Check if a given object implements the BacktestReplayWithEmbeddings200Response interface.
 */
export function instanceOfBacktestReplayWithEmbeddings200Response(value: object): value is BacktestReplayWithEmbeddings200Response {
    return true;
}

export function BacktestReplayWithEmbeddings200ResponseFromJSON(json: any): BacktestReplayWithEmbeddings200Response {
    return BacktestReplayWithEmbeddings200ResponseFromJSONTyped(json, false);
}

export function BacktestReplayWithEmbeddings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacktestReplayWithEmbeddings200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(BacktestEventFromJSON)),
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
        'meta': json['meta'] == null ? undefined : BacktestReplayWithEmbeddings200ResponseMetaFromJSON(json['meta']),
    };
}

export function BacktestReplayWithEmbeddings200ResponseToJSON(value?: BacktestReplayWithEmbeddings200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ok': value['ok'],
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(BacktestEventToJSON)),
        'next_cursor': value['nextCursor'],
        'has_more': value['hasMore'],
        'meta': BacktestReplayWithEmbeddings200ResponseMetaToJSON(value['meta']),
    };
}

