/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BacktestEmbeddingFilter } from './BacktestEmbeddingFilter';
import {
    BacktestEmbeddingFilterFromJSON,
    BacktestEmbeddingFilterFromJSONTyped,
    BacktestEmbeddingFilterToJSON,
} from './BacktestEmbeddingFilter';

/**
 * 
 * @export
 * @interface BacktestReplayWithEmbeddingsRequest
 */
export interface BacktestReplayWithEmbeddingsRequest {
    /**
     * Start of time range (Unix milliseconds)
     * @type {number}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    from: number;
    /**
     * End of time range (Unix milliseconds)
     * @type {number}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    to: number;
    /**
     * Topic classes: `articles`, `stories`
     * @type {Array<string>}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    topics?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    categories?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    sources?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    keywords?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    entities?: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    includeEmbeddings?: boolean;
    /**
     * Max 1 embedding filter per request
     * @type {Array<BacktestEmbeddingFilter>}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    embeddingFilters?: Array<BacktestEmbeddingFilter>;
    /**
     * 
     * @type {number}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    cursor?: number;
    /**
     * 
     * @type {number}
     * @memberof BacktestReplayWithEmbeddingsRequest
     */
    limit?: number;
}

/**
 * Check if a given object implements the BacktestReplayWithEmbeddingsRequest interface.
 */
export function instanceOfBacktestReplayWithEmbeddingsRequest(value: object): value is BacktestReplayWithEmbeddingsRequest {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function BacktestReplayWithEmbeddingsRequestFromJSON(json: any): BacktestReplayWithEmbeddingsRequest {
    return BacktestReplayWithEmbeddingsRequestFromJSONTyped(json, false);
}

export function BacktestReplayWithEmbeddingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacktestReplayWithEmbeddingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'topics': json['topics'] == null ? undefined : json['topics'],
        'categories': json['categories'] == null ? undefined : json['categories'],
        'sources': json['sources'] == null ? undefined : json['sources'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'entities': json['entities'] == null ? undefined : json['entities'],
        'includeEmbeddings': json['include_embeddings'] == null ? undefined : json['include_embeddings'],
        'embeddingFilters': json['embedding_filters'] == null ? undefined : ((json['embedding_filters'] as Array<any>).map(BacktestEmbeddingFilterFromJSON)),
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function BacktestReplayWithEmbeddingsRequestToJSON(value?: BacktestReplayWithEmbeddingsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'],
        'to': value['to'],
        'topics': value['topics'],
        'categories': value['categories'],
        'sources': value['sources'],
        'keywords': value['keywords'],
        'entities': value['entities'],
        'include_embeddings': value['includeEmbeddings'],
        'embedding_filters': value['embeddingFilters'] == null ? undefined : ((value['embeddingFilters'] as Array<any>).map(BacktestEmbeddingFilterToJSON)),
        'cursor': value['cursor'],
        'limit': value['limit'],
    };
}

