/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BacktestEvent
 */
export interface BacktestEvent {
    /**
     * 
     * @type {number}
     * @memberof BacktestEvent
     */
    id?: number;
    /**
     * Event timestamp (Unix milliseconds)
     * @type {number}
     * @memberof BacktestEvent
     */
    ts?: number;
    /**
     * 
     * @type {string}
     * @memberof BacktestEvent
     */
    eventType?: BacktestEventEventTypeEnum;
    /**
     * Story cluster ID (0 for article-only events)
     * @type {number}
     * @memberof BacktestEvent
     */
    clusterId?: number;
    /**
     * The original WebSocket event payload
     * @type {object}
     * @memberof BacktestEvent
     */
    payload?: object;
    /**
     * Cosine similarity score (only present when embedding filter is active)
     * @type {number}
     * @memberof BacktestEvent
     */
    similarity?: number;
    /**
     * Embedding vector (only present when include_embeddings=true)
     * @type {Array<number>}
     * @memberof BacktestEvent
     */
    embedding?: Array<number>;
}


/**
 * @export
 */
export const BacktestEventEventTypeEnum = {
    ItemNew: 'item.new',
    ItemEnriched: 'item.enriched',
    StoryDevelopment: 'story.development',
    StoryPriorityChanged: 'story.priority_changed',
    ClusterEvent: 'cluster.event',
    ClustersRanked: 'clusters.ranked'
} as const;
export type BacktestEventEventTypeEnum = typeof BacktestEventEventTypeEnum[keyof typeof BacktestEventEventTypeEnum];


/**
 * Check if a given object implements the BacktestEvent interface.
 */
export function instanceOfBacktestEvent(value: object): value is BacktestEvent {
    return true;
}

export function BacktestEventFromJSON(json: any): BacktestEvent {
    return BacktestEventFromJSONTyped(json, false);
}

export function BacktestEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacktestEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ts': json['ts'] == null ? undefined : json['ts'],
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'clusterId': json['cluster_id'] == null ? undefined : json['cluster_id'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'similarity': json['similarity'] == null ? undefined : json['similarity'],
        'embedding': json['embedding'] == null ? undefined : json['embedding'],
    };
}

export function BacktestEventToJSON(value?: BacktestEvent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'ts': value['ts'],
        'event_type': value['eventType'],
        'cluster_id': value['clusterId'],
        'payload': value['payload'],
        'similarity': value['similarity'],
        'embedding': value['embedding'],
    };
}

