/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BacktestReplay200ResponseMeta
 */
export interface BacktestReplay200ResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof BacktestReplay200ResponseMeta
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof BacktestReplay200ResponseMeta
     */
    to?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof BacktestReplay200ResponseMeta
     */
    topics?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof BacktestReplay200ResponseMeta
     */
    filtersApplied?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {number}
     * @memberof BacktestReplay200ResponseMeta
     */
    eventCount?: number;
}

/**
 * Check if a given object implements the BacktestReplay200ResponseMeta interface.
 */
export function instanceOfBacktestReplay200ResponseMeta(value: object): value is BacktestReplay200ResponseMeta {
    return true;
}

export function BacktestReplay200ResponseMetaFromJSON(json: any): BacktestReplay200ResponseMeta {
    return BacktestReplay200ResponseMetaFromJSONTyped(json, false);
}

export function BacktestReplay200ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacktestReplay200ResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : json['from'],
        'to': json['to'] == null ? undefined : json['to'],
        'topics': json['topics'] == null ? undefined : json['topics'],
        'filtersApplied': json['filters_applied'] == null ? undefined : json['filters_applied'],
        'eventCount': json['event_count'] == null ? undefined : json['event_count'],
    };
}

export function BacktestReplay200ResponseMetaToJSON(value?: BacktestReplay200ResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'],
        'to': value['to'],
        'topics': value['topics'],
        'filters_applied': value['filtersApplied'],
        'event_count': value['eventCount'],
    };
}

