/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityDetail
 */
export interface EntityDetail {
    /**
     * 
     * @type {number}
     * @memberof EntityDetail
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityDetail
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityDetail
     */
    type?: EntityDetailTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EntityDetail
     */
    subcategory?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityDetail
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityDetail
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityDetail
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityDetail
     */
    wikidataId?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityDetail
     */
    wikipediaUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityDetail
     */
    articleCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntityDetail
     */
    aliases?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EntityDetail
     */
    enriched?: boolean;
}


/**
 * @export
 */
export const EntityDetailTypeEnum = {
    Person: 'person',
    Org: 'org',
    Location: 'location'
} as const;
export type EntityDetailTypeEnum = typeof EntityDetailTypeEnum[keyof typeof EntityDetailTypeEnum];


/**
 * Check if a given object implements the EntityDetail interface.
 */
export function instanceOfEntityDetail(value: object): value is EntityDetail {
    return true;
}

export function EntityDetailFromJSON(json: any): EntityDetail {
    return EntityDetailFromJSONTyped(json, false);
}

export function EntityDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'wikidataId': json['wikidata_id'] == null ? undefined : json['wikidata_id'],
        'wikipediaUrl': json['wikipedia_url'] == null ? undefined : json['wikipedia_url'],
        'articleCount': json['article_count'] == null ? undefined : json['article_count'],
        'aliases': json['aliases'] == null ? undefined : json['aliases'],
        'enriched': json['enriched'] == null ? undefined : json['enriched'],
    };
}

export function EntityDetailToJSON(value?: EntityDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'subcategory': value['subcategory'],
        'slug': value['slug'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'wikidata_id': value['wikidataId'],
        'wikipedia_url': value['wikipediaUrl'],
        'article_count': value['articleCount'],
        'aliases': value['aliases'],
        'enriched': value['enriched'],
    };
}

