/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface GetArticle200Response
 */
export interface GetArticle200Response {
    /**
     * 
     * @type {Item}
     * @memberof GetArticle200Response
     */
    item?: Item;
}

/**
 * Check if a given object implements the GetArticle200Response interface.
 */
export function instanceOfGetArticle200Response(value: object): value is GetArticle200Response {
    return true;
}

export function GetArticle200ResponseFromJSON(json: any): GetArticle200Response {
    return GetArticle200ResponseFromJSONTyped(json, false);
}

export function GetArticle200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetArticle200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'item': json['item'] == null ? undefined : ItemFromJSON(json['item']),
    };
}

export function GetArticle200ResponseToJSON(value?: GetArticle200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'item': ItemToJSON(value['item']),
    };
}

