/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEmbedding200Response
 */
export interface GetEmbedding200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetEmbedding200Response
     */
    ok?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetEmbedding200Response
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEmbedding200Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEmbedding200Response
     */
    model?: string;
    /**
     * 
     * @type {number}
     * @memberof GetEmbedding200Response
     */
    dimensions?: number;
    /**
     * Embedding vector as float array, or base64 string when embedding_format=base64
     * @type {Array<number>}
     * @memberof GetEmbedding200Response
     */
    embedding?: Array<number>;
}

/**
 * Check if a given object implements the GetEmbedding200Response interface.
 */
export function instanceOfGetEmbedding200Response(value: object): value is GetEmbedding200Response {
    return true;
}

export function GetEmbedding200ResponseFromJSON(json: any): GetEmbedding200Response {
    return GetEmbedding200ResponseFromJSONTyped(json, false);
}

export function GetEmbedding200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmbedding200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'model': json['model'] == null ? undefined : json['model'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'embedding': json['embedding'] == null ? undefined : json['embedding'],
    };
}

export function GetEmbedding200ResponseToJSON(value?: GetEmbedding200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ok': value['ok'],
        'type': value['type'],
        'id': value['id'],
        'model': value['model'],
        'dimensions': value['dimensions'],
        'embedding': value['embedding'],
    };
}

