/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GraphNode } from './GraphNode';
import {
    GraphNodeFromJSON,
    GraphNodeFromJSONTyped,
    GraphNodeToJSON,
} from './GraphNode';
import type { GraphEdge } from './GraphEdge';
import {
    GraphEdgeFromJSON,
    GraphEdgeFromJSONTyped,
    GraphEdgeToJSON,
} from './GraphEdge';

/**
 * 
 * @export
 * @interface GetEntityNetwork200Response
 */
export interface GetEntityNetwork200Response {
    /**
     * 
     * @type {Array<GraphNode>}
     * @memberof GetEntityNetwork200Response
     */
    nodes?: Array<GraphNode>;
    /**
     * 
     * @type {Array<GraphEdge>}
     * @memberof GetEntityNetwork200Response
     */
    edges?: Array<GraphEdge>;
}

/**
 * Check if a given object implements the GetEntityNetwork200Response interface.
 */
export function instanceOfGetEntityNetwork200Response(value: object): value is GetEntityNetwork200Response {
    return true;
}

export function GetEntityNetwork200ResponseFromJSON(json: any): GetEntityNetwork200Response {
    return GetEntityNetwork200ResponseFromJSONTyped(json, false);
}

export function GetEntityNetwork200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEntityNetwork200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': json['nodes'] == null ? undefined : ((json['nodes'] as Array<any>).map(GraphNodeFromJSON)),
        'edges': json['edges'] == null ? undefined : ((json['edges'] as Array<any>).map(GraphEdgeFromJSON)),
    };
}

export function GetEntityNetwork200ResponseToJSON(value?: GetEntityNetwork200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodes': value['nodes'] == null ? undefined : ((value['nodes'] as Array<any>).map(GraphNodeToJSON)),
        'edges': value['edges'] == null ? undefined : ((value['edges'] as Array<any>).map(GraphEdgeToJSON)),
    };
}

