/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetStoryEntityGraph200ResponseEdgesInner } from './GetStoryEntityGraph200ResponseEdgesInner';
import {
    GetStoryEntityGraph200ResponseEdgesInnerFromJSON,
    GetStoryEntityGraph200ResponseEdgesInnerFromJSONTyped,
    GetStoryEntityGraph200ResponseEdgesInnerToJSON,
} from './GetStoryEntityGraph200ResponseEdgesInner';
import type { EntityDetail } from './EntityDetail';
import {
    EntityDetailFromJSON,
    EntityDetailFromJSONTyped,
    EntityDetailToJSON,
} from './EntityDetail';
import type { Story } from './Story';
import {
    StoryFromJSON,
    StoryFromJSONTyped,
    StoryToJSON,
} from './Story';

/**
 * 
 * @export
 * @interface GetStoryEntityGraph200Response
 */
export interface GetStoryEntityGraph200Response {
    /**
     * 
     * @type {Story}
     * @memberof GetStoryEntityGraph200Response
     */
    story?: Story;
    /**
     * 
     * @type {Array<EntityDetail>}
     * @memberof GetStoryEntityGraph200Response
     */
    entities?: Array<EntityDetail>;
    /**
     * 
     * @type {Array<GetStoryEntityGraph200ResponseEdgesInner>}
     * @memberof GetStoryEntityGraph200Response
     */
    edges?: Array<GetStoryEntityGraph200ResponseEdgesInner>;
}

/**
 * Check if a given object implements the GetStoryEntityGraph200Response interface.
 */
export function instanceOfGetStoryEntityGraph200Response(value: object): value is GetStoryEntityGraph200Response {
    return true;
}

export function GetStoryEntityGraph200ResponseFromJSON(json: any): GetStoryEntityGraph200Response {
    return GetStoryEntityGraph200ResponseFromJSONTyped(json, false);
}

export function GetStoryEntityGraph200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStoryEntityGraph200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'story': json['story'] == null ? undefined : StoryFromJSON(json['story']),
        'entities': json['entities'] == null ? undefined : ((json['entities'] as Array<any>).map(EntityDetailFromJSON)),
        'edges': json['edges'] == null ? undefined : ((json['edges'] as Array<any>).map(GetStoryEntityGraph200ResponseEdgesInnerFromJSON)),
    };
}

export function GetStoryEntityGraph200ResponseToJSON(value?: GetStoryEntityGraph200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'story': StoryToJSON(value['story']),
        'entities': value['entities'] == null ? undefined : ((value['entities'] as Array<any>).map(EntityDetailToJSON)),
        'edges': value['edges'] == null ? undefined : ((value['edges'] as Array<any>).map(GetStoryEntityGraph200ResponseEdgesInnerToJSON)),
    };
}

