/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStoryEntityGraph200ResponseEdgesInner
 */
export interface GetStoryEntityGraph200ResponseEdgesInner {
    /**
     * 
     * @type {number}
     * @memberof GetStoryEntityGraph200ResponseEdgesInner
     */
    storyId?: number;
    /**
     * 
     * @type {number}
     * @memberof GetStoryEntityGraph200ResponseEdgesInner
     */
    entityId?: number;
    /**
     * 
     * @type {number}
     * @memberof GetStoryEntityGraph200ResponseEdgesInner
     */
    mentionCount?: number;
}

/**
 * Check if a given object implements the GetStoryEntityGraph200ResponseEdgesInner interface.
 */
export function instanceOfGetStoryEntityGraph200ResponseEdgesInner(value: object): value is GetStoryEntityGraph200ResponseEdgesInner {
    return true;
}

export function GetStoryEntityGraph200ResponseEdgesInnerFromJSON(json: any): GetStoryEntityGraph200ResponseEdgesInner {
    return GetStoryEntityGraph200ResponseEdgesInnerFromJSONTyped(json, false);
}

export function GetStoryEntityGraph200ResponseEdgesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStoryEntityGraph200ResponseEdgesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'storyId': json['story_id'] == null ? undefined : json['story_id'],
        'entityId': json['entity_id'] == null ? undefined : json['entity_id'],
        'mentionCount': json['mention_count'] == null ? undefined : json['mention_count'],
    };
}

export function GetStoryEntityGraph200ResponseEdgesInnerToJSON(value?: GetStoryEntityGraph200ResponseEdgesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'story_id': value['storyId'],
        'entity_id': value['entityId'],
        'mention_count': value['mentionCount'],
    };
}

