/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetTopicClusterGraph200ResponseTopicsInner } from './GetTopicClusterGraph200ResponseTopicsInner';
import {
    GetTopicClusterGraph200ResponseTopicsInnerFromJSON,
    GetTopicClusterGraph200ResponseTopicsInnerFromJSONTyped,
    GetTopicClusterGraph200ResponseTopicsInnerToJSON,
} from './GetTopicClusterGraph200ResponseTopicsInner';

/**
 * 
 * @export
 * @interface GetTopicClusterGraph200Response
 */
export interface GetTopicClusterGraph200Response {
    /**
     * 
     * @type {Array<GetTopicClusterGraph200ResponseTopicsInner>}
     * @memberof GetTopicClusterGraph200Response
     */
    topics?: Array<GetTopicClusterGraph200ResponseTopicsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetTopicClusterGraph200Response
     */
    count?: number;
}

/**
 * Check if a given object implements the GetTopicClusterGraph200Response interface.
 */
export function instanceOfGetTopicClusterGraph200Response(value: object): value is GetTopicClusterGraph200Response {
    return true;
}

export function GetTopicClusterGraph200ResponseFromJSON(json: any): GetTopicClusterGraph200Response {
    return GetTopicClusterGraph200ResponseFromJSONTyped(json, false);
}

export function GetTopicClusterGraph200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTopicClusterGraph200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'topics': json['topics'] == null ? undefined : ((json['topics'] as Array<any>).map(GetTopicClusterGraph200ResponseTopicsInnerFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function GetTopicClusterGraph200ResponseToJSON(value?: GetTopicClusterGraph200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'topics': value['topics'] == null ? undefined : ((value['topics'] as Array<any>).map(GetTopicClusterGraph200ResponseTopicsInnerToJSON)),
        'count': value['count'],
    };
}

