/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Story } from './Story';
import {
    StoryFromJSON,
    StoryFromJSONTyped,
    StoryToJSON,
} from './Story';

/**
 * 
 * @export
 * @interface GetTopicClusterGraph200ResponseTopicsInner
 */
export interface GetTopicClusterGraph200ResponseTopicsInner {
    /**
     * 
     * @type {number}
     * @memberof GetTopicClusterGraph200ResponseTopicsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetTopicClusterGraph200ResponseTopicsInner
     */
    headline?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTopicClusterGraph200ResponseTopicsInner
     */
    category?: string;
    /**
     * 
     * @type {Array<Story>}
     * @memberof GetTopicClusterGraph200ResponseTopicsInner
     */
    eventClusters?: Array<Story>;
}

/**
 * Check if a given object implements the GetTopicClusterGraph200ResponseTopicsInner interface.
 */
export function instanceOfGetTopicClusterGraph200ResponseTopicsInner(value: object): value is GetTopicClusterGraph200ResponseTopicsInner {
    return true;
}

export function GetTopicClusterGraph200ResponseTopicsInnerFromJSON(json: any): GetTopicClusterGraph200ResponseTopicsInner {
    return GetTopicClusterGraph200ResponseTopicsInnerFromJSONTyped(json, false);
}

export function GetTopicClusterGraph200ResponseTopicsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTopicClusterGraph200ResponseTopicsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'headline': json['headline'] == null ? undefined : json['headline'],
        'category': json['category'] == null ? undefined : json['category'],
        'eventClusters': json['event_clusters'] == null ? undefined : ((json['event_clusters'] as Array<any>).map(StoryFromJSON)),
    };
}

export function GetTopicClusterGraph200ResponseTopicsInnerToJSON(value?: GetTopicClusterGraph200ResponseTopicsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'headline': value['headline'],
        'category': value['category'],
        'event_clusters': value['eventClusters'] == null ? undefined : ((value['eventClusters'] as Array<any>).map(StoryToJSON)),
    };
}

