/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUsage200ResponseDailyInner
 */
export interface GetUsage200ResponseDailyInner {
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseDailyInner
     */
    dayMs?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseDailyInner
     */
    requests?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseDailyInner
     */
    errors?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseDailyInner
     */
    bytes?: number;
}

/**
 * Check if a given object implements the GetUsage200ResponseDailyInner interface.
 */
export function instanceOfGetUsage200ResponseDailyInner(value: object): value is GetUsage200ResponseDailyInner {
    return true;
}

export function GetUsage200ResponseDailyInnerFromJSON(json: any): GetUsage200ResponseDailyInner {
    return GetUsage200ResponseDailyInnerFromJSONTyped(json, false);
}

export function GetUsage200ResponseDailyInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsage200ResponseDailyInner {
    if (json == null) {
        return json;
    }
    return {
        
        'dayMs': json['day_ms'] == null ? undefined : json['day_ms'],
        'requests': json['requests'] == null ? undefined : json['requests'],
        'errors': json['errors'] == null ? undefined : json['errors'],
        'bytes': json['bytes'] == null ? undefined : json['bytes'],
    };
}

export function GetUsage200ResponseDailyInnerToJSON(value?: GetUsage200ResponseDailyInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'day_ms': value['dayMs'],
        'requests': value['requests'],
        'errors': value['errors'],
        'bytes': value['bytes'],
    };
}

