/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUsage200ResponseSummary } from './GetUsage200ResponseSummary';
import {
    GetUsage200ResponseSummaryFromJSON,
    GetUsage200ResponseSummaryFromJSONTyped,
    GetUsage200ResponseSummaryToJSON,
} from './GetUsage200ResponseSummary';
import type { GetUsage200ResponseDailyInner } from './GetUsage200ResponseDailyInner';
import {
    GetUsage200ResponseDailyInnerFromJSON,
    GetUsage200ResponseDailyInnerFromJSONTyped,
    GetUsage200ResponseDailyInnerToJSON,
} from './GetUsage200ResponseDailyInner';
import type { GetUsage200ResponseQuota } from './GetUsage200ResponseQuota';
import {
    GetUsage200ResponseQuotaFromJSON,
    GetUsage200ResponseQuotaFromJSONTyped,
    GetUsage200ResponseQuotaToJSON,
} from './GetUsage200ResponseQuota';

/**
 * 
 * @export
 * @interface GetUsage200Response
 */
export interface GetUsage200Response {
    /**
     * 
     * @type {string}
     * @memberof GetUsage200Response
     */
    keyId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsage200Response
     */
    tier?: string;
    /**
     * 
     * @type {GetUsage200ResponseQuota}
     * @memberof GetUsage200Response
     */
    quota?: GetUsage200ResponseQuota;
    /**
     * 
     * @type {GetUsage200ResponseSummary}
     * @memberof GetUsage200Response
     */
    summary?: GetUsage200ResponseSummary;
    /**
     * 
     * @type {Array<GetUsage200ResponseDailyInner>}
     * @memberof GetUsage200Response
     */
    daily?: Array<GetUsage200ResponseDailyInner>;
}

/**
 * Check if a given object implements the GetUsage200Response interface.
 */
export function instanceOfGetUsage200Response(value: object): value is GetUsage200Response {
    return true;
}

export function GetUsage200ResponseFromJSON(json: any): GetUsage200Response {
    return GetUsage200ResponseFromJSONTyped(json, false);
}

export function GetUsage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'keyId': json['key_id'] == null ? undefined : json['key_id'],
        'tier': json['tier'] == null ? undefined : json['tier'],
        'quota': json['quota'] == null ? undefined : GetUsage200ResponseQuotaFromJSON(json['quota']),
        'summary': json['summary'] == null ? undefined : GetUsage200ResponseSummaryFromJSON(json['summary']),
        'daily': json['daily'] == null ? undefined : ((json['daily'] as Array<any>).map(GetUsage200ResponseDailyInnerFromJSON)),
    };
}

export function GetUsage200ResponseToJSON(value?: GetUsage200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key_id': value['keyId'],
        'tier': value['tier'],
        'quota': GetUsage200ResponseQuotaToJSON(value['quota']),
        'summary': GetUsage200ResponseSummaryToJSON(value['summary']),
        'daily': value['daily'] == null ? undefined : ((value['daily'] as Array<any>).map(GetUsage200ResponseDailyInnerToJSON)),
    };
}

