/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUsage200ResponseQuota
 */
export interface GetUsage200ResponseQuota {
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseQuota
     */
    monthlyLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseQuota
     */
    monthlyUsed?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseQuota
     */
    pctUsed?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseQuota
     */
    graceLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseQuota
     */
    resetsAtMs?: number;
}

/**
 * Check if a given object implements the GetUsage200ResponseQuota interface.
 */
export function instanceOfGetUsage200ResponseQuota(value: object): value is GetUsage200ResponseQuota {
    return true;
}

export function GetUsage200ResponseQuotaFromJSON(json: any): GetUsage200ResponseQuota {
    return GetUsage200ResponseQuotaFromJSONTyped(json, false);
}

export function GetUsage200ResponseQuotaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsage200ResponseQuota {
    if (json == null) {
        return json;
    }
    return {
        
        'monthlyLimit': json['monthly_limit'] == null ? undefined : json['monthly_limit'],
        'monthlyUsed': json['monthly_used'] == null ? undefined : json['monthly_used'],
        'pctUsed': json['pct_used'] == null ? undefined : json['pct_used'],
        'graceLimit': json['grace_limit'] == null ? undefined : json['grace_limit'],
        'resetsAtMs': json['resets_at_ms'] == null ? undefined : json['resets_at_ms'],
    };
}

export function GetUsage200ResponseQuotaToJSON(value?: GetUsage200ResponseQuota | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'monthly_limit': value['monthlyLimit'],
        'monthly_used': value['monthlyUsed'],
        'pct_used': value['pctUsed'],
        'grace_limit': value['graceLimit'],
        'resets_at_ms': value['resetsAtMs'],
    };
}

