/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUsage200ResponseSummaryTopEndpointsInner } from './GetUsage200ResponseSummaryTopEndpointsInner';
import {
    GetUsage200ResponseSummaryTopEndpointsInnerFromJSON,
    GetUsage200ResponseSummaryTopEndpointsInnerFromJSONTyped,
    GetUsage200ResponseSummaryTopEndpointsInnerToJSON,
} from './GetUsage200ResponseSummaryTopEndpointsInner';

/**
 * 
 * @export
 * @interface GetUsage200ResponseSummary
 */
export interface GetUsage200ResponseSummary {
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseSummary
     */
    totalRequests?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseSummary
     */
    totalBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseSummary
     */
    totalErrors?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseSummary
     */
    avgLatencyMs?: number;
    /**
     * 
     * @type {Array<GetUsage200ResponseSummaryTopEndpointsInner>}
     * @memberof GetUsage200ResponseSummary
     */
    topEndpoints?: Array<GetUsage200ResponseSummaryTopEndpointsInner>;
}

/**
 * Check if a given object implements the GetUsage200ResponseSummary interface.
 */
export function instanceOfGetUsage200ResponseSummary(value: object): value is GetUsage200ResponseSummary {
    return true;
}

export function GetUsage200ResponseSummaryFromJSON(json: any): GetUsage200ResponseSummary {
    return GetUsage200ResponseSummaryFromJSONTyped(json, false);
}

export function GetUsage200ResponseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsage200ResponseSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalRequests': json['total_requests'] == null ? undefined : json['total_requests'],
        'totalBytes': json['total_bytes'] == null ? undefined : json['total_bytes'],
        'totalErrors': json['total_errors'] == null ? undefined : json['total_errors'],
        'avgLatencyMs': json['avg_latency_ms'] == null ? undefined : json['avg_latency_ms'],
        'topEndpoints': json['top_endpoints'] == null ? undefined : ((json['top_endpoints'] as Array<any>).map(GetUsage200ResponseSummaryTopEndpointsInnerFromJSON)),
    };
}

export function GetUsage200ResponseSummaryToJSON(value?: GetUsage200ResponseSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total_requests': value['totalRequests'],
        'total_bytes': value['totalBytes'],
        'total_errors': value['totalErrors'],
        'avg_latency_ms': value['avgLatencyMs'],
        'top_endpoints': value['topEndpoints'] == null ? undefined : ((value['topEndpoints'] as Array<any>).map(GetUsage200ResponseSummaryTopEndpointsInnerToJSON)),
    };
}

