/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUsage200ResponseSummaryTopEndpointsInner
 */
export interface GetUsage200ResponseSummaryTopEndpointsInner {
    /**
     * 
     * @type {string}
     * @memberof GetUsage200ResponseSummaryTopEndpointsInner
     */
    endpoint?: string;
    /**
     * 
     * @type {number}
     * @memberof GetUsage200ResponseSummaryTopEndpointsInner
     */
    count?: number;
}

/**
 * Check if a given object implements the GetUsage200ResponseSummaryTopEndpointsInner interface.
 */
export function instanceOfGetUsage200ResponseSummaryTopEndpointsInner(value: object): value is GetUsage200ResponseSummaryTopEndpointsInner {
    return true;
}

export function GetUsage200ResponseSummaryTopEndpointsInnerFromJSON(json: any): GetUsage200ResponseSummaryTopEndpointsInner {
    return GetUsage200ResponseSummaryTopEndpointsInnerFromJSONTyped(json, false);
}

export function GetUsage200ResponseSummaryTopEndpointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsage200ResponseSummaryTopEndpointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function GetUsage200ResponseSummaryTopEndpointsInnerToJSON(value?: GetUsage200ResponseSummaryTopEndpointsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'endpoint': value['endpoint'],
        'count': value['count'],
    };
}

