/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphNode
 */
export interface GraphNode {
    /**
     * 
     * @type {number}
     * @memberof GraphNode
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    type?: GraphNodeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    slug?: string;
}


/**
 * @export
 */
export const GraphNodeTypeEnum = {
    Person: 'person',
    Org: 'org',
    Location: 'location'
} as const;
export type GraphNodeTypeEnum = typeof GraphNodeTypeEnum[keyof typeof GraphNodeTypeEnum];


/**
 * Check if a given object implements the GraphNode interface.
 */
export function instanceOfGraphNode(value: object): value is GraphNode {
    return true;
}

export function GraphNodeFromJSON(json: any): GraphNode {
    return GraphNodeFromJSONTyped(json, false);
}

export function GraphNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function GraphNodeToJSON(value?: GraphNode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'slug': value['slug'],
    };
}

