/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GraphNode } from './GraphNode';
import {
    GraphNodeFromJSON,
    GraphNodeFromJSONTyped,
    GraphNodeToJSON,
} from './GraphNode';

/**
 * 
 * @export
 * @interface GraphEdge
 */
export interface GraphEdge {
    /**
     * 
     * @type {number}
     * @memberof GraphEdge
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphEdge
     */
    sourceEntityId?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphEdge
     */
    targetEntityId?: number;
    /**
     * 
     * @type {string}
     * @memberof GraphEdge
     */
    relationshipType?: string;
    /**
     * 
     * @type {number}
     * @memberof GraphEdge
     */
    confidence?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphEdge
     */
    articleCount?: number;
    /**
     * 
     * @type {GraphNode}
     * @memberof GraphEdge
     */
    sourceEntity?: GraphNode;
    /**
     * 
     * @type {GraphNode}
     * @memberof GraphEdge
     */
    targetEntity?: GraphNode;
}

/**
 * Check if a given object implements the GraphEdge interface.
 */
export function instanceOfGraphEdge(value: object): value is GraphEdge {
    return true;
}

export function GraphEdgeFromJSON(json: any): GraphEdge {
    return GraphEdgeFromJSONTyped(json, false);
}

export function GraphEdgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphEdge {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sourceEntityId': json['source_entity_id'] == null ? undefined : json['source_entity_id'],
        'targetEntityId': json['target_entity_id'] == null ? undefined : json['target_entity_id'],
        'relationshipType': json['relationship_type'] == null ? undefined : json['relationship_type'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'articleCount': json['article_count'] == null ? undefined : json['article_count'],
        'sourceEntity': json['source_entity'] == null ? undefined : GraphNodeFromJSON(json['source_entity']),
        'targetEntity': json['target_entity'] == null ? undefined : GraphNodeFromJSON(json['target_entity']),
    };
}

export function GraphEdgeToJSON(value?: GraphEdge | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'source_entity_id': value['sourceEntityId'],
        'target_entity_id': value['targetEntityId'],
        'relationship_type': value['relationshipType'],
        'confidence': value['confidence'],
        'article_count': value['articleCount'],
        'source_entity': GraphNodeToJSON(value['sourceEntity']),
        'target_entity': GraphNodeToJSON(value['targetEntity']),
    };
}

