/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    urlHash?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    sourceId?: number;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    sourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    category?: string;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof Item
     */
    publishedAt?: number;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof Item
     */
    discoveredAt?: number;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    excerpt?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    contentStatus?: ItemContentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    headlineSummary?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    slug?: string;
}


/**
 * @export
 */
export const ItemContentStatusEnum = {
    HasContent: 'has_content',
    NoContent: 'no_content',
    Failed: 'failed'
} as const;
export type ItemContentStatusEnum = typeof ItemContentStatusEnum[keyof typeof ItemContentStatusEnum];


/**
 * Check if a given object implements the Item interface.
 */
export function instanceOfItem(value: object): value is Item {
    return true;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'urlHash': json['url_hash'] == null ? undefined : json['url_hash'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
        'sourceId': json['source_id'] == null ? undefined : json['source_id'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'category': json['category'] == null ? undefined : json['category'],
        'publishedAt': json['published_at'] == null ? undefined : json['published_at'],
        'discoveredAt': json['discovered_at'] == null ? undefined : json['discovered_at'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'contentStatus': json['content_status'] == null ? undefined : json['content_status'],
        'headlineSummary': json['headline_summary'] == null ? undefined : json['headline_summary'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function ItemToJSON(value?: Item | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'url_hash': value['urlHash'],
        'title': value['title'],
        'url': value['url'],
        'source_id': value['sourceId'],
        'source_name': value['sourceName'],
        'category': value['category'],
        'published_at': value['publishedAt'],
        'discovered_at': value['discoveredAt'],
        'excerpt': value['excerpt'],
        'image_url': value['imageUrl'],
        'content_status': value['contentStatus'],
        'headline_summary': value['headlineSummary'],
        'slug': value['slug'],
    };
}

