/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryDevelopment } from './StoryDevelopment';
import {
    StoryDevelopmentFromJSON,
    StoryDevelopmentFromJSONTyped,
    StoryDevelopmentToJSON,
} from './StoryDevelopment';

/**
 * 
 * @export
 * @interface ListStoryDevelopments200Response
 */
export interface ListStoryDevelopments200Response {
    /**
     * 
     * @type {Array<StoryDevelopment>}
     * @memberof ListStoryDevelopments200Response
     */
    developments?: Array<StoryDevelopment>;
    /**
     * 
     * @type {number}
     * @memberof ListStoryDevelopments200Response
     */
    count?: number;
}

/**
 * Check if a given object implements the ListStoryDevelopments200Response interface.
 */
export function instanceOfListStoryDevelopments200Response(value: object): value is ListStoryDevelopments200Response {
    return true;
}

export function ListStoryDevelopments200ResponseFromJSON(json: any): ListStoryDevelopments200Response {
    return ListStoryDevelopments200ResponseFromJSONTyped(json, false);
}

export function ListStoryDevelopments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListStoryDevelopments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'developments': json['developments'] == null ? undefined : ((json['developments'] as Array<any>).map(StoryDevelopmentFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function ListStoryDevelopments200ResponseToJSON(value?: ListStoryDevelopments200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'developments': value['developments'] == null ? undefined : ((value['developments'] as Array<any>).map(StoryDevelopmentToJSON)),
        'count': value['count'],
    };
}

