/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SourceRanking } from './SourceRanking';
import {
    SourceRankingFromJSON,
    SourceRankingFromJSONTyped,
    SourceRankingToJSON,
} from './SourceRanking';

/**
 * 
 * @export
 * @interface ListSourceRankings200Response
 */
export interface ListSourceRankings200Response {
    /**
     * 
     * @type {Array<SourceRanking>}
     * @memberof ListSourceRankings200Response
     */
    rankings?: Array<SourceRanking>;
    /**
     * 
     * @type {number}
     * @memberof ListSourceRankings200Response
     */
    count?: number;
}

/**
 * Check if a given object implements the ListSourceRankings200Response interface.
 */
export function instanceOfListSourceRankings200Response(value: object): value is ListSourceRankings200Response {
    return true;
}

export function ListSourceRankings200ResponseFromJSON(json: any): ListSourceRankings200Response {
    return ListSourceRankings200ResponseFromJSONTyped(json, false);
}

export function ListSourceRankings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSourceRankings200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'rankings': json['rankings'] == null ? undefined : ((json['rankings'] as Array<any>).map(SourceRankingFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function ListSourceRankings200ResponseToJSON(value?: ListSourceRankings200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rankings': value['rankings'] == null ? undefined : ((value['rankings'] as Array<any>).map(SourceRankingToJSON)),
        'count': value['count'],
    };
}

