/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface ListEntityArticles200Response
 */
export interface ListEntityArticles200Response {
    /**
     * 
     * @type {Array<Item>}
     * @memberof ListEntityArticles200Response
     */
    items?: Array<Item>;
    /**
     * 
     * @type {number}
     * @memberof ListEntityArticles200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ListEntityArticles200Response
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof ListEntityArticles200Response
     */
    limit?: number;
}

/**
 * Check if a given object implements the ListEntityArticles200Response interface.
 */
export function instanceOfListEntityArticles200Response(value: object): value is ListEntityArticles200Response {
    return true;
}

export function ListEntityArticles200ResponseFromJSON(json: any): ListEntityArticles200Response {
    return ListEntityArticles200ResponseFromJSONTyped(json, false);
}

export function ListEntityArticles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEntityArticles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ItemFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function ListEntityArticles200ResponseToJSON(value?: ListEntityArticles200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ItemToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

