/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Story } from './Story';
import {
    StoryFromJSON,
    StoryFromJSONTyped,
    StoryToJSON,
} from './Story';

/**
 * 
 * @export
 * @interface ListStories200Response
 */
export interface ListStories200Response {
    /**
     * 
     * @type {Array<Story>}
     * @memberof ListStories200Response
     */
    stories?: Array<Story>;
}

/**
 * Check if a given object implements the ListStories200Response interface.
 */
export function instanceOfListStories200Response(value: object): value is ListStories200Response {
    return true;
}

export function ListStories200ResponseFromJSON(json: any): ListStories200Response {
    return ListStories200ResponseFromJSONTyped(json, false);
}

export function ListStories200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListStories200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'stories': json['stories'] == null ? undefined : ((json['stories'] as Array<any>).map(StoryFromJSON)),
    };
}

export function ListStories200ResponseToJSON(value?: ListStories200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stories': value['stories'] == null ? undefined : ((value['stories'] as Array<any>).map(StoryToJSON)),
    };
}

