/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityDetail } from './EntityDetail';
import {
    EntityDetailFromJSON,
    EntityDetailFromJSONTyped,
    EntityDetailToJSON,
} from './EntityDetail';

/**
 * 
 * @export
 * @interface ListPoliticians200Response
 */
export interface ListPoliticians200Response {
    /**
     * 
     * @type {Array<EntityDetail>}
     * @memberof ListPoliticians200Response
     */
    entities?: Array<EntityDetail>;
    /**
     * 
     * @type {number}
     * @memberof ListPoliticians200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ListPoliticians200Response
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof ListPoliticians200Response
     */
    limit?: number;
}

/**
 * Check if a given object implements the ListPoliticians200Response interface.
 */
export function instanceOfListPoliticians200Response(value: object): value is ListPoliticians200Response {
    return true;
}

export function ListPoliticians200ResponseFromJSON(json: any): ListPoliticians200Response {
    return ListPoliticians200ResponseFromJSONTyped(json, false);
}

export function ListPoliticians200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPoliticians200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'entities': json['entities'] == null ? undefined : ((json['entities'] as Array<any>).map(EntityDetailFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function ListPoliticians200ResponseToJSON(value?: ListPoliticians200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'entities': value['entities'] == null ? undefined : ((value['entities'] as Array<any>).map(EntityDetailToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

