/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityDetail } from './EntityDetail';
import {
    EntityDetailFromJSON,
    EntityDetailFromJSONTyped,
    EntityDetailToJSON,
} from './EntityDetail';

/**
 * 
 * @export
 * @interface ListTrendingEntities200Response
 */
export interface ListTrendingEntities200Response {
    /**
     * 
     * @type {Array<EntityDetail>}
     * @memberof ListTrendingEntities200Response
     */
    entities?: Array<EntityDetail>;
}

/**
 * Check if a given object implements the ListTrendingEntities200Response interface.
 */
export function instanceOfListTrendingEntities200Response(value: object): value is ListTrendingEntities200Response {
    return true;
}

export function ListTrendingEntities200ResponseFromJSON(json: any): ListTrendingEntities200Response {
    return ListTrendingEntities200ResponseFromJSONTyped(json, false);
}

export function ListTrendingEntities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTrendingEntities200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'entities': json['entities'] == null ? undefined : ((json['entities'] as Array<any>).map(EntityDetailFromJSON)),
    };
}

export function ListTrendingEntities200ResponseToJSON(value?: ListTrendingEntities200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'entities': value['entities'] == null ? undefined : ((value['entities'] as Array<any>).map(EntityDetailToJSON)),
    };
}

