/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    urlHashHex?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    sourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchResult
     */
    publishedAtMs?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchResult
     */
    discoveredAtMs?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    placeholderImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    snippet?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchResult
     */
    rank?: number;
}

/**
 * Check if a given object implements the SearchResult interface.
 */
export function instanceOfSearchResult(value: object): value is SearchResult {
    return true;
}

export function SearchResultFromJSON(json: any): SearchResult {
    return SearchResultFromJSONTyped(json, false);
}

export function SearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'urlHashHex': json['url_hash_hex'] == null ? undefined : json['url_hash_hex'],
        'title': json['title'] == null ? undefined : json['title'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'category': json['category'] == null ? undefined : json['category'],
        'publishedAtMs': json['published_at_ms'] == null ? undefined : json['published_at_ms'],
        'discoveredAtMs': json['discovered_at_ms'] == null ? undefined : json['discovered_at_ms'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'placeholderImageUrl': json['placeholder_image_url'] == null ? undefined : json['placeholder_image_url'],
        'snippet': json['snippet'] == null ? undefined : json['snippet'],
        'rank': json['rank'] == null ? undefined : json['rank'],
    };
}

export function SearchResultToJSON(value?: SearchResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url_hash_hex': value['urlHashHex'],
        'title': value['title'],
        'source_name': value['sourceName'],
        'category': value['category'],
        'published_at_ms': value['publishedAtMs'],
        'discovered_at_ms': value['discoveredAtMs'],
        'image_url': value['imageUrl'],
        'placeholder_image_url': value['placeholderImageUrl'],
        'snippet': value['snippet'],
        'rank': value['rank'],
    };
}

