/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface SearchArticles200Response
 */
export interface SearchArticles200Response {
    /**
     * 
     * @type {Array<Item>}
     * @memberof SearchArticles200Response
     */
    items?: Array<Item>;
    /**
     * 
     * @type {number}
     * @memberof SearchArticles200Response
     */
    total?: number;
}

/**
 * Check if a given object implements the SearchArticles200Response interface.
 */
export function instanceOfSearchArticles200Response(value: object): value is SearchArticles200Response {
    return true;
}

export function SearchArticles200ResponseFromJSON(json: any): SearchArticles200Response {
    return SearchArticles200ResponseFromJSONTyped(json, false);
}

export function SearchArticles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchArticles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ItemFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function SearchArticles200ResponseToJSON(value?: SearchArticles200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ItemToJSON)),
        'total': value['total'],
    };
}

