/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchSuggest200Response
 */
export interface SearchSuggest200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchSuggest200Response
     */
    suggestions?: Array<string>;
}

/**
 * Check if a given object implements the SearchSuggest200Response interface.
 */
export function instanceOfSearchSuggest200Response(value: object): value is SearchSuggest200Response {
    return true;
}

export function SearchSuggest200ResponseFromJSON(json: any): SearchSuggest200Response {
    return SearchSuggest200ResponseFromJSONTyped(json, false);
}

export function SearchSuggest200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSuggest200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestions': json['suggestions'] == null ? undefined : json['suggestions'],
    };
}

export function SearchSuggest200ResponseToJSON(value?: SearchSuggest200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'suggestions': value['suggestions'],
    };
}

