/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResult } from './SearchResult';
import {
    SearchResultFromJSON,
    SearchResultFromJSONTyped,
    SearchResultToJSON,
} from './SearchResult';

/**
 * 
 * @export
 * @interface SearchFull200Response
 */
export interface SearchFull200Response {
    /**
     * 
     * @type {Array<SearchResult>}
     * @memberof SearchFull200Response
     */
    results?: Array<SearchResult>;
    /**
     * 
     * @type {number}
     * @memberof SearchFull200Response
     */
    total?: number;
}

/**
 * Check if a given object implements the SearchFull200Response interface.
 */
export function instanceOfSearchFull200Response(value: object): value is SearchFull200Response {
    return true;
}

export function SearchFull200ResponseFromJSON(json: any): SearchFull200Response {
    return SearchFull200ResponseFromJSONTyped(json, false);
}

export function SearchFull200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchFull200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SearchResultFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function SearchFull200ResponseToJSON(value?: SearchFull200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SearchResultToJSON)),
        'total': value['total'],
    };
}

