/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceRanking
 */
export interface SourceRanking {
    /**
     * 
     * @type {string}
     * @memberof SourceRanking
     */
    sourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceRanking
     */
    sourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceRanking
     */
    logoUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    firstToClusterScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    clusterFrequencyScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    speedScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    topicalAuthorityScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    contentDiversityScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    extractionSuccessScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    neutralityScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    sensationalismScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    reliabilityScore?: number;
    /**
     * 
     * @type {number}
     * @memberof SourceRanking
     */
    overallScore?: number;
    /**
     * 
     * @type {string}
     * @memberof SourceRanking
     */
    tier?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceRanking
     */
    descriptionOneLiner?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceRanking
     */
    descriptionSummary?: string;
}

/**
 * Check if a given object implements the SourceRanking interface.
 */
export function instanceOfSourceRanking(value: object): value is SourceRanking {
    return true;
}

export function SourceRankingFromJSON(json: any): SourceRanking {
    return SourceRankingFromJSONTyped(json, false);
}

export function SourceRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceId': json['source_id'] == null ? undefined : json['source_id'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'firstToClusterScore': json['first_to_cluster_score'] == null ? undefined : json['first_to_cluster_score'],
        'clusterFrequencyScore': json['cluster_frequency_score'] == null ? undefined : json['cluster_frequency_score'],
        'speedScore': json['speed_score'] == null ? undefined : json['speed_score'],
        'topicalAuthorityScore': json['topical_authority_score'] == null ? undefined : json['topical_authority_score'],
        'contentDiversityScore': json['content_diversity_score'] == null ? undefined : json['content_diversity_score'],
        'extractionSuccessScore': json['extraction_success_score'] == null ? undefined : json['extraction_success_score'],
        'neutralityScore': json['neutrality_score'] == null ? undefined : json['neutrality_score'],
        'sensationalismScore': json['sensationalism_score'] == null ? undefined : json['sensationalism_score'],
        'reliabilityScore': json['reliability_score'] == null ? undefined : json['reliability_score'],
        'overallScore': json['overall_score'] == null ? undefined : json['overall_score'],
        'tier': json['tier'] == null ? undefined : json['tier'],
        'descriptionOneLiner': json['description_one_liner'] == null ? undefined : json['description_one_liner'],
        'descriptionSummary': json['description_summary'] == null ? undefined : json['description_summary'],
    };
}

export function SourceRankingToJSON(value?: SourceRanking | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'source_id': value['sourceId'],
        'source_name': value['sourceName'],
        'logo_url': value['logoUrl'],
        'first_to_cluster_score': value['firstToClusterScore'],
        'cluster_frequency_score': value['clusterFrequencyScore'],
        'speed_score': value['speedScore'],
        'topical_authority_score': value['topicalAuthorityScore'],
        'content_diversity_score': value['contentDiversityScore'],
        'extraction_success_score': value['extractionSuccessScore'],
        'neutrality_score': value['neutralityScore'],
        'sensationalism_score': value['sensationalismScore'],
        'reliability_score': value['reliabilityScore'],
        'overall_score': value['overallScore'],
        'tier': value['tier'],
        'description_one_liner': value['descriptionOneLiner'],
        'description_summary': value['descriptionSummary'],
    };
}

