/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stats
 */
export interface Stats {
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    totalArticles?: number;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    totalStories?: number;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    totalEntities?: number;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    totalSources?: number;
}

/**
 * Check if a given object implements the Stats interface.
 */
export function instanceOfStats(value: object): value is Stats {
    return true;
}

export function StatsFromJSON(json: any): Stats {
    return StatsFromJSONTyped(json, false);
}

export function StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalArticles': json['total_articles'] == null ? undefined : json['total_articles'],
        'totalStories': json['total_stories'] == null ? undefined : json['total_stories'],
        'totalEntities': json['total_entities'] == null ? undefined : json['total_entities'],
        'totalSources': json['total_sources'] == null ? undefined : json['total_sources'],
    };
}

export function StatsToJSON(value?: Stats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total_articles': value['totalArticles'],
        'total_stories': value['totalStories'],
        'total_entities': value['totalEntities'],
        'total_sources': value['totalSources'],
    };
}

