/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryDevelopment
 */
export interface StoryDevelopment {
    /**
     * 
     * @type {number}
     * @memberof StoryDevelopment
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryDevelopment
     */
    clusterId?: number;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof StoryDevelopment
     */
    createdAtMs?: number;
    /**
     * 
     * @type {string}
     * @memberof StoryDevelopment
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryDevelopment
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryDevelopment
     */
    significance?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryDevelopment
     */
    previousHeadline?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryDevelopment
     */
    newHeadline?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoryDevelopment
     */
    triggerArticleHashes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof StoryDevelopment
     */
    enrichmentSeq?: number;
}

/**
 * Check if a given object implements the StoryDevelopment interface.
 */
export function instanceOfStoryDevelopment(value: object): value is StoryDevelopment {
    return true;
}

export function StoryDevelopmentFromJSON(json: any): StoryDevelopment {
    return StoryDevelopmentFromJSONTyped(json, false);
}

export function StoryDevelopmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryDevelopment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'clusterId': json['cluster_id'] == null ? undefined : json['cluster_id'],
        'createdAtMs': json['created_at_ms'] == null ? undefined : json['created_at_ms'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'significance': json['significance'] == null ? undefined : json['significance'],
        'previousHeadline': json['previous_headline'] == null ? undefined : json['previous_headline'],
        'newHeadline': json['new_headline'] == null ? undefined : json['new_headline'],
        'triggerArticleHashes': json['trigger_article_hashes'] == null ? undefined : json['trigger_article_hashes'],
        'enrichmentSeq': json['enrichment_seq'] == null ? undefined : json['enrichment_seq'],
    };
}

export function StoryDevelopmentToJSON(value?: StoryDevelopment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'cluster_id': value['clusterId'],
        'created_at_ms': value['createdAtMs'],
        'title': value['title'],
        'description': value['description'],
        'significance': value['significance'],
        'previous_headline': value['previousHeadline'],
        'new_headline': value['newHeadline'],
        'trigger_article_hashes': value['triggerArticleHashes'],
        'enrichment_seq': value['enrichmentSeq'],
    };
}

