/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';
import type { StoryDevelopment } from './StoryDevelopment';
import {
    StoryDevelopmentFromJSON,
    StoryDevelopmentFromJSONTyped,
    StoryDevelopmentToJSON,
} from './StoryDevelopment';

/**
 * 
 * @export
 * @interface StoryDetail
 */
export interface StoryDetail {
    /**
     * 
     * @type {number}
     * @memberof StoryDetail
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof StoryDetail
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryDetail
     */
    headline?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryDetail
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryDetail
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof StoryDetail
     */
    articleCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoryDetail
     */
    sources?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoryDetail
     */
    topEntities?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof StoryDetail
     */
    category?: string;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof StoryDetail
     */
    firstSeen?: number;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof StoryDetail
     */
    lastUpdated?: number;
    /**
     * 
     * @type {string}
     * @memberof StoryDetail
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryDetail
     */
    richSummary?: string;
    /**
     * 
     * @type {Array<Item>}
     * @memberof StoryDetail
     */
    articles?: Array<Item>;
    /**
     * 
     * @type {Array<StoryDevelopment>}
     * @memberof StoryDetail
     */
    developments?: Array<StoryDevelopment>;
}

/**
 * Check if a given object implements the StoryDetail interface.
 */
export function instanceOfStoryDetail(value: object): value is StoryDetail {
    return true;
}

export function StoryDetailFromJSON(json: any): StoryDetail {
    return StoryDetailFromJSONTyped(json, false);
}

export function StoryDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'headline': json['headline'] == null ? undefined : json['headline'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'articleCount': json['article_count'] == null ? undefined : json['article_count'],
        'sources': json['sources'] == null ? undefined : json['sources'],
        'topEntities': json['top_entities'] == null ? undefined : json['top_entities'],
        'category': json['category'] == null ? undefined : json['category'],
        'firstSeen': json['first_seen'] == null ? undefined : json['first_seen'],
        'lastUpdated': json['last_updated'] == null ? undefined : json['last_updated'],
        'label': json['label'] == null ? undefined : json['label'],
        'richSummary': json['rich_summary'] == null ? undefined : json['rich_summary'],
        'articles': json['articles'] == null ? undefined : ((json['articles'] as Array<any>).map(ItemFromJSON)),
        'developments': json['developments'] == null ? undefined : ((json['developments'] as Array<any>).map(StoryDevelopmentFromJSON)),
    };
}

export function StoryDetailToJSON(value?: StoryDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'headline': value['headline'],
        'summary': value['summary'],
        'image_url': value['imageUrl'],
        'article_count': value['articleCount'],
        'sources': value['sources'],
        'top_entities': value['topEntities'],
        'category': value['category'],
        'first_seen': value['firstSeen'],
        'last_updated': value['lastUpdated'],
        'label': value['label'],
        'rich_summary': value['richSummary'],
        'articles': value['articles'] == null ? undefined : ((value['articles'] as Array<any>).map(ItemToJSON)),
        'developments': value['developments'] == null ? undefined : ((value['developments'] as Array<any>).map(StoryDevelopmentToJSON)),
    };
}

