/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Story
 */
export interface Story {
    /**
     * 
     * @type {number}
     * @memberof Story
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Story
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Story
     */
    headline?: string;
    /**
     * 
     * @type {string}
     * @memberof Story
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof Story
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Story
     */
    articleCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Story
     */
    sources?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Story
     */
    topEntities?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Story
     */
    category?: string;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof Story
     */
    firstSeen?: number;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof Story
     */
    lastUpdated?: number;
    /**
     * 
     * @type {string}
     * @memberof Story
     */
    label?: string;
}

/**
 * Check if a given object implements the Story interface.
 */
export function instanceOfStory(value: object): value is Story {
    return true;
}

export function StoryFromJSON(json: any): Story {
    return StoryFromJSONTyped(json, false);
}

export function StoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Story {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'headline': json['headline'] == null ? undefined : json['headline'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'articleCount': json['article_count'] == null ? undefined : json['article_count'],
        'sources': json['sources'] == null ? undefined : json['sources'],
        'topEntities': json['top_entities'] == null ? undefined : json['top_entities'],
        'category': json['category'] == null ? undefined : json['category'],
        'firstSeen': json['first_seen'] == null ? undefined : json['first_seen'],
        'lastUpdated': json['last_updated'] == null ? undefined : json['last_updated'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function StoryToJSON(value?: Story | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'headline': value['headline'],
        'summary': value['summary'],
        'image_url': value['imageUrl'],
        'article_count': value['articleCount'],
        'sources': value['sources'],
        'top_entities': value['topEntities'],
        'category': value['category'],
        'first_seen': value['firstSeen'],
        'last_updated': value['lastUpdated'],
        'label': value['label'],
    };
}

