/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryUpdateSignalNewArticlesInner } from './StoryUpdateSignalNewArticlesInner';
import {
    StoryUpdateSignalNewArticlesInnerFromJSON,
    StoryUpdateSignalNewArticlesInnerFromJSONTyped,
    StoryUpdateSignalNewArticlesInnerToJSON,
} from './StoryUpdateSignalNewArticlesInner';

/**
 * 
 * @export
 * @interface StoryUpdateSignal
 */
export interface StoryUpdateSignal {
    /**
     * 
     * @type {number}
     * @memberof StoryUpdateSignal
     */
    clusterId?: number;
    /**
     * 
     * @type {Array<StoryUpdateSignalNewArticlesInner>}
     * @memberof StoryUpdateSignal
     */
    newArticles?: Array<StoryUpdateSignalNewArticlesInner>;
    /**
     * 
     * @type {number}
     * @memberof StoryUpdateSignal
     */
    newArticleCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoryUpdateSignal
     */
    newSources?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoryUpdateSignal
     */
    newEntities?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof StoryUpdateSignal
     */
    significance?: StoryUpdateSignalSignificanceEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoryUpdateSignal
     */
    significanceReasons?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof StoryUpdateSignal
     */
    baselineMemberCount?: number;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof StoryUpdateSignal
     */
    checkedAtMs?: number;
}


/**
 * @export
 */
export const StoryUpdateSignalSignificanceEnum = {
    None: 'none',
    Minor: 'minor',
    Moderate: 'moderate',
    Major: 'major'
} as const;
export type StoryUpdateSignalSignificanceEnum = typeof StoryUpdateSignalSignificanceEnum[keyof typeof StoryUpdateSignalSignificanceEnum];


/**
 * Check if a given object implements the StoryUpdateSignal interface.
 */
export function instanceOfStoryUpdateSignal(value: object): value is StoryUpdateSignal {
    return true;
}

export function StoryUpdateSignalFromJSON(json: any): StoryUpdateSignal {
    return StoryUpdateSignalFromJSONTyped(json, false);
}

export function StoryUpdateSignalFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryUpdateSignal {
    if (json == null) {
        return json;
    }
    return {
        
        'clusterId': json['cluster_id'] == null ? undefined : json['cluster_id'],
        'newArticles': json['new_articles'] == null ? undefined : ((json['new_articles'] as Array<any>).map(StoryUpdateSignalNewArticlesInnerFromJSON)),
        'newArticleCount': json['new_article_count'] == null ? undefined : json['new_article_count'],
        'newSources': json['new_sources'] == null ? undefined : json['new_sources'],
        'newEntities': json['new_entities'] == null ? undefined : json['new_entities'],
        'significance': json['significance'] == null ? undefined : json['significance'],
        'significanceReasons': json['significance_reasons'] == null ? undefined : json['significance_reasons'],
        'baselineMemberCount': json['baseline_member_count'] == null ? undefined : json['baseline_member_count'],
        'checkedAtMs': json['checked_at_ms'] == null ? undefined : json['checked_at_ms'],
    };
}

export function StoryUpdateSignalToJSON(value?: StoryUpdateSignal | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cluster_id': value['clusterId'],
        'new_articles': value['newArticles'] == null ? undefined : ((value['newArticles'] as Array<any>).map(StoryUpdateSignalNewArticlesInnerToJSON)),
        'new_article_count': value['newArticleCount'],
        'new_sources': value['newSources'],
        'new_entities': value['newEntities'],
        'significance': value['significance'],
        'significance_reasons': value['significanceReasons'],
        'baseline_member_count': value['baselineMemberCount'],
        'checked_at_ms': value['checkedAtMs'],
    };
}

