/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryUpdateSignalNewArticlesInner
 */
export interface StoryUpdateSignalNewArticlesInner {
    /**
     * 
     * @type {string}
     * @memberof StoryUpdateSignalNewArticlesInner
     */
    urlHash?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryUpdateSignalNewArticlesInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryUpdateSignalNewArticlesInner
     */
    sourceName?: string;
    /**
     * 
     * @type {number}
     * @memberof StoryUpdateSignalNewArticlesInner
     */
    publishedAt?: number;
}

/**
 * Check if a given object implements the StoryUpdateSignalNewArticlesInner interface.
 */
export function instanceOfStoryUpdateSignalNewArticlesInner(value: object): value is StoryUpdateSignalNewArticlesInner {
    return true;
}

export function StoryUpdateSignalNewArticlesInnerFromJSON(json: any): StoryUpdateSignalNewArticlesInner {
    return StoryUpdateSignalNewArticlesInnerFromJSONTyped(json, false);
}

export function StoryUpdateSignalNewArticlesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryUpdateSignalNewArticlesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'urlHash': json['url_hash'] == null ? undefined : json['url_hash'],
        'title': json['title'] == null ? undefined : json['title'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'publishedAt': json['published_at'] == null ? undefined : json['published_at'],
    };
}

export function StoryUpdateSignalNewArticlesInnerToJSON(value?: StoryUpdateSignalNewArticlesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url_hash': value['urlHash'],
        'title': value['title'],
        'source_name': value['sourceName'],
        'published_at': value['publishedAt'],
    };
}

