/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VectorSearchRequest
 */
export interface VectorSearchRequest {
    /**
     * 1536-dimensional embedding vector (OpenAI text-embedding-3-small compatible)
     * @type {Array<number>}
     * @memberof VectorSearchRequest
     */
    embedding: Array<number>;
    /**
     * Which result types to include
     * @type {Array<string>}
     * @memberof VectorSearchRequest
     */
    types?: Array<VectorSearchRequestTypesEnum>;
    /**
     * Only search content from the last N hours
     * @type {number}
     * @memberof VectorSearchRequest
     */
    sinceHours?: number;
    /**
     * Maximum results per type
     * @type {number}
     * @memberof VectorSearchRequest
     */
    limit?: number;
}


/**
 * @export
 */
export const VectorSearchRequestTypesEnum = {
    Article: 'article',
    Story: 'story'
} as const;
export type VectorSearchRequestTypesEnum = typeof VectorSearchRequestTypesEnum[keyof typeof VectorSearchRequestTypesEnum];


/**
 * Check if a given object implements the VectorSearchRequest interface.
 */
export function instanceOfVectorSearchRequest(value: object): value is VectorSearchRequest {
    if (!('embedding' in value) || value['embedding'] === undefined) return false;
    return true;
}

export function VectorSearchRequestFromJSON(json: any): VectorSearchRequest {
    return VectorSearchRequestFromJSONTyped(json, false);
}

export function VectorSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorSearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'embedding': json['embedding'],
        'types': json['types'] == null ? undefined : json['types'],
        'sinceHours': json['since_hours'] == null ? undefined : json['since_hours'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function VectorSearchRequestToJSON(value?: VectorSearchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'embedding': value['embedding'],
        'types': value['types'],
        'since_hours': value['sinceHours'],
        'limit': value['limit'],
    };
}

