/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VectorSearch200ResponseArticlesInner
 */
export interface VectorSearch200ResponseArticlesInner {
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseArticlesInner
     */
    similarity?: number;
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseArticlesInner
     */
    distance?: number;
    /**
     * 
     * @type {string}
     * @memberof VectorSearch200ResponseArticlesInner
     */
    urlHash?: string;
    /**
     * 
     * @type {string}
     * @memberof VectorSearch200ResponseArticlesInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof VectorSearch200ResponseArticlesInner
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof VectorSearch200ResponseArticlesInner
     */
    sourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof VectorSearch200ResponseArticlesInner
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseArticlesInner
     */
    publishedAt?: number;
}

/**
 * Check if a given object implements the VectorSearch200ResponseArticlesInner interface.
 */
export function instanceOfVectorSearch200ResponseArticlesInner(value: object): value is VectorSearch200ResponseArticlesInner {
    return true;
}

export function VectorSearch200ResponseArticlesInnerFromJSON(json: any): VectorSearch200ResponseArticlesInner {
    return VectorSearch200ResponseArticlesInnerFromJSONTyped(json, false);
}

export function VectorSearch200ResponseArticlesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorSearch200ResponseArticlesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'similarity': json['similarity'] == null ? undefined : json['similarity'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'urlHash': json['url_hash'] == null ? undefined : json['url_hash'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'category': json['category'] == null ? undefined : json['category'],
        'publishedAt': json['published_at'] == null ? undefined : json['published_at'],
    };
}

export function VectorSearch200ResponseArticlesInnerToJSON(value?: VectorSearch200ResponseArticlesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'similarity': value['similarity'],
        'distance': value['distance'],
        'url_hash': value['urlHash'],
        'title': value['title'],
        'url': value['url'],
        'source_name': value['sourceName'],
        'category': value['category'],
        'published_at': value['publishedAt'],
    };
}

