/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VectorSearch200ResponseStoriesInner } from './VectorSearch200ResponseStoriesInner';
import {
    VectorSearch200ResponseStoriesInnerFromJSON,
    VectorSearch200ResponseStoriesInnerFromJSONTyped,
    VectorSearch200ResponseStoriesInnerToJSON,
} from './VectorSearch200ResponseStoriesInner';
import type { VectorSearch200ResponseArticlesInner } from './VectorSearch200ResponseArticlesInner';
import {
    VectorSearch200ResponseArticlesInnerFromJSON,
    VectorSearch200ResponseArticlesInnerFromJSONTyped,
    VectorSearch200ResponseArticlesInnerToJSON,
} from './VectorSearch200ResponseArticlesInner';

/**
 * 
 * @export
 * @interface VectorSearch200Response
 */
export interface VectorSearch200Response {
    /**
     * 
     * @type {boolean}
     * @memberof VectorSearch200Response
     */
    ok?: boolean;
    /**
     * 
     * @type {Array<VectorSearch200ResponseArticlesInner>}
     * @memberof VectorSearch200Response
     */
    articles?: Array<VectorSearch200ResponseArticlesInner>;
    /**
     * 
     * @type {Array<VectorSearch200ResponseStoriesInner>}
     * @memberof VectorSearch200Response
     */
    stories?: Array<VectorSearch200ResponseStoriesInner>;
}

/**
 * Check if a given object implements the VectorSearch200Response interface.
 */
export function instanceOfVectorSearch200Response(value: object): value is VectorSearch200Response {
    return true;
}

export function VectorSearch200ResponseFromJSON(json: any): VectorSearch200Response {
    return VectorSearch200ResponseFromJSONTyped(json, false);
}

export function VectorSearch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorSearch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
        'articles': json['articles'] == null ? undefined : ((json['articles'] as Array<any>).map(VectorSearch200ResponseArticlesInnerFromJSON)),
        'stories': json['stories'] == null ? undefined : ((json['stories'] as Array<any>).map(VectorSearch200ResponseStoriesInnerFromJSON)),
    };
}

export function VectorSearch200ResponseToJSON(value?: VectorSearch200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ok': value['ok'],
        'articles': value['articles'] == null ? undefined : ((value['articles'] as Array<any>).map(VectorSearch200ResponseArticlesInnerToJSON)),
        'stories': value['stories'] == null ? undefined : ((value['stories'] as Array<any>).map(VectorSearch200ResponseStoriesInnerToJSON)),
    };
}

