/* tslint:disable */
/* eslint-disable */
/**
 * NewsRank API
 * The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VectorSearch200ResponseStoriesInner
 */
export interface VectorSearch200ResponseStoriesInner {
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseStoriesInner
     */
    similarity?: number;
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseStoriesInner
     */
    distance?: number;
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseStoriesInner
     */
    clusterId?: number;
    /**
     * 
     * @type {string}
     * @memberof VectorSearch200ResponseStoriesInner
     */
    headline?: string;
    /**
     * 
     * @type {string}
     * @memberof VectorSearch200ResponseStoriesInner
     */
    summary?: string;
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseStoriesInner
     */
    articleCount?: number;
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseStoriesInner
     */
    firstSeen?: number;
    /**
     * 
     * @type {number}
     * @memberof VectorSearch200ResponseStoriesInner
     */
    lastUpdated?: number;
}

/**
 * Check if a given object implements the VectorSearch200ResponseStoriesInner interface.
 */
export function instanceOfVectorSearch200ResponseStoriesInner(value: object): value is VectorSearch200ResponseStoriesInner {
    return true;
}

export function VectorSearch200ResponseStoriesInnerFromJSON(json: any): VectorSearch200ResponseStoriesInner {
    return VectorSearch200ResponseStoriesInnerFromJSONTyped(json, false);
}

export function VectorSearch200ResponseStoriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorSearch200ResponseStoriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'similarity': json['similarity'] == null ? undefined : json['similarity'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'clusterId': json['cluster_id'] == null ? undefined : json['cluster_id'],
        'headline': json['headline'] == null ? undefined : json['headline'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'articleCount': json['article_count'] == null ? undefined : json['article_count'],
        'firstSeen': json['first_seen'] == null ? undefined : json['first_seen'],
        'lastUpdated': json['last_updated'] == null ? undefined : json['last_updated'],
    };
}

export function VectorSearch200ResponseStoriesInnerToJSON(value?: VectorSearch200ResponseStoriesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'similarity': value['similarity'],
        'distance': value['distance'],
        'cluster_id': value['clusterId'],
        'headline': value['headline'],
        'summary': value['summary'],
        'article_count': value['articleCount'],
        'first_seen': value['firstSeen'],
        'last_updated': value['lastUpdated'],
    };
}

